[package]
name = "aws-instance"
version = "0.1.0"
authors = ["Jack Lund <jackl@geekheads.net>"]
edition = "2018"

[dependencies]
clap = "2.30.0"
serde_derive = "1.0.27"
serde = "1.0.27"
rusoto_core = "0.36.0"
rusoto_ec2 = "0.36.0"
rusoto_credential = "0.15.0"
log = "0.4.1"
env_logger = "0.5.3"
lazy_static = "1.2.0"
regex = "1.1.0"
dirs = "1.0.4"
